name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: main  

      - id: get_sha
        name: Get latest sha
        run: |
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=sha::$SHA"
            
      - run: |
          echo "Hello ${{ steps.get_sha.outputs.sha }}!"
          echo "- in ${{ github.event.inputs.home }}!"
